name: News from onlinekhabar
'on':
  schedule:
    - cron: 55 4 * * 0-5
  workflow_dispatch: null
jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Scrapy spider
        run: scrapy runspider ./scripts/khabar.py -O onlinekbr.json
      - name: Commit changes
        run: |
          git config --global Ashim Shakya '${{ secrets.MAIN_USERNAME }}'
          git config --global ashim44shakya@gmail.com '${{ secrets.MAIN_EMAIL }}'
          git add -f onlinekbr.json
          git commit -m "Update onlinekbr.json"
          git push
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
